CREATE TABLE CSE532.DEA_NY (
REPORTER_DEA_NO varchar(10),
REPORTER_BUS_ACT varchar(50),
REPORTER_NAME varchar(50),
REPORTER_ADDL_CO_INFO varchar(50),
REPORTER_ADDRESS1 varchar(50),
REPORTER_ADDRESS2 varchar(50),
REPORTER_CITY varchar(20),
REPORTER_STATE varchar(4),
REPORTER_ZIP int NOT NULL,
REPORTER_COUNTY varchar(20),
BUYER_DEA_NO varchar(10),
BUYER_BUS_ACT varchar(50),
BUYER_NAME varchar(70),
BUYER_ADDL_CO_INFO varchar(70),
BUYER_ADDRESS1 varchar(50),
BUYER_ADDRESS2 varchar(50),
BUYER_CITY varchar(50),
BUYER_STATE varchar(4),
BUYER_ZIP int NOT NULL,
BUYER_COUNTY varchar(20),
TRANSACTION_CODE varchar(20),
DRUG_CODE varchar(20),
NDC_NO varchar(12),
DRUG_NAME varchar(20),
QUANTITY varchar(20),
UNIT varchar(20),
ACTION_INDICATOR varchar(20),
ORDER_FORM_NO varchar(20),
CORRECTION_NO varchar(20),
STRENGTH varchar(20),
TRANSACTION_DATE DATE NOT NULL,
CALC_BASE_WT_IN_GM varchar(20),
DOSAGE_UNIT real NOT NULL,
TRANSACTION_ID varchar(11),
Product_Name varchar(50),
Ingredient_Name varchar(50),
Measure varchar(20),
MME_Conversion_Factor varchar(20),
Combined_Labeler_Name varchar(50),
Reporter_family varchar(50),
dos_str varchar(20),
MME real NOT NULL
) COMPRESS YES;
