WITH DEA_DB AS (
	SELECT YEAR(TRANSACTION_DATE) ||
		CASE
			WHEN (CAST(MONTH(TRANSACTION_DATE) AS INT) < 10)
			THEN '0' || CAST(MONTH(TRANSACTION_DATE) AS INT)
		ELSE CAST(MONTH(TRANSACTION_DATE) AS CHAR(2))
		END AS YRMN_ALL, DOSAGE_UNIT AS DOS
	FROM CSE532.DEA_NY
	ORDER BY TRANSACTION_DATE
),
FINAL_DB AS (
	SELECT SUM(DOS) AS DOSAGE, YRMN_ALL AS MONTH_OF_YEAR
	FROM DEA_DB
	GROUP BY YRMN_ALL
)

SELECT MONTH_OF_YEAR, DOSAGE,
AVG (DOSAGE) OVER (ORDER BY MONTH_OF_YEAR ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) AS SMOOTH2_DOSAGE
FROM FINAL_DB;