WITH DEA_DB AS (
	SELECT SUM(MME) AS TOTAL_MME, BUYER_ZIP
	FROM CSE532.DEA_NY
	GROUP BY BUYER_ZIP
),
Z_DB AS (
	SELECT ZIP, ZPOP
	FROM CSE532.ZIPPOP
	WHERE ZPOP <> 0
),
RESULT_DB AS (
	SELECT DEA_DB.BUYER_ZIP AS ZIP_R, DEA_DB.TOTAL_MME, Z_DB.ZPOP, DEA_DB.TOTAL_MME / Z_DB.ZPOP AS RESULT, DENSE_RANK() OVER(ORDER BY DEA_DB.TOTAL_MME / Z_DB.ZPOP DESC) RES_RANK
	FROM Z_DB INNER JOIN DEA_DB
	ON DEA_DB.BUYER_ZIP = Z_DB.ZIP
)

SELECT ZIP_R, RESULT, RES_RANK
FROM RESULT_DB
WHERE RES_RANK <= 5;